#!/usr/bin/env python3
"""
T6: Generate enforcement-spec.yml from kind:gate REQ-IDs.
Reads all non-deprecated kind:gate requirements from the ESE corpus
and outputs a machine-readable YAML enforcement specification.

Usage: python3 _generate_enforcement_spec.py <repo_root> <file1> [file2 ...]
Output: YAML to stdout.
"""
import sys
import re
import os
import datetime

repo_root = sys.argv[1]
files = sys.argv[2:]

FENCE = "```"

gates = []

for filepath in files:
    relpath = os.path.relpath(filepath, repo_root)
    try:
        with open(filepath, encoding="utf-8") as f:
            lines = f.readlines()
    except Exception:
        continue

    in_fence = False
    i = 0
    while i < len(lines):
        line = lines[i].rstrip("\n")
        if line.startswith(FENCE):
            in_fence = not in_fence
            i += 1
            continue
        if in_fence:
            i += 1
            continue

        anchor = re.match(r'<a name="(REQ-[^"]+)"></a>', line)
        if anchor:
            req_id = anchor.group(1)
            tag_line = lines[i+1].rstrip("\n") if i+1 < len(lines) else ""
            stmt_line = lines[i+2].rstrip("\n") if i+2 < len(lines) else ""

            tags = re.findall(r"`([^`]+)`", tag_line)

            # Only kind:gate, non-deprecated
            if not tags or tags[0] != "gate":
                i += 3
                continue
            if any(t.startswith("deprecated:") for t in tags):
                i += 3
                continue

            kind        = tags[0]                             # gate
            scope       = tags[1] if len(tags) > 1 else ""
            enforcement = tags[2] if len(tags) > 2 else ""
            applies_when= tags[3] if len(tags) > 3 else "all"
            eval_scope  = tags[4] if len(tags) > 4 else ""

            # Clean statement (strip markdown, strikethrough)
            stmt = re.sub(r"~~.*?~~", "", stmt_line).strip()
            stmt = re.sub(r"\*\*([^*]+)\*\*", r"\1", stmt)
            stmt = re.sub(r"`([^`]+)`", r"\1", stmt)
            stmt = stmt.strip()

            gates.append({
                "id":           req_id,
                "scope":        scope,
                "enforcement":  enforcement,
                "applies_when": applies_when,
                "eval_scope":   eval_scope,
                "statement":    stmt,
                "source":       relpath,
            })
            i += 3
            continue
        i += 1

gates.sort(key=lambda g: g["id"])
generated_at = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

# YAML output (no external deps)
def yaml_str(s):
    """Quote a string for YAML if it contains special characters."""
    if not s:
        return '""'
    if any(c in s for c in (':', '#', '{', '}', '[', ']', ',', '&', '*', '?',
                             '|', '-', '<', '>', '=', '!', '%', '@', '`', '"', "'")):
        escaped = s.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return s

lines_out = []
lines_out.append("# ESE Enforcement Specification")
lines_out.append("# Auto-generated by scripts/generate-enforcement-spec.sh")
lines_out.append("# Source: STANDARDS.md, 7 addenda, adoption.md, templates, starters")
lines_out.append("# Do not edit by hand — regenerate with: bash scripts/generate-enforcement-spec.sh generate")
lines_out.append(f"# Generated: {generated_at}")
lines_out.append("#")
lines_out.append(f"# Total gates: {len(gates)}")
lines_out.append("")
lines_out.append(f"version: \"1.0\"")
lines_out.append(f"generated: \"{generated_at}\"")
lines_out.append(f"gate_count: {len(gates)}")
lines_out.append("gates:")
for g in gates:
    lines_out.append(f"  - id: {g['id']}")
    lines_out.append(f"    status: active")
    lines_out.append(f"    mode: deterministic")
    lines_out.append(f"    scope: {g['scope']}")
    lines_out.append(f"    enforcement: {g['enforcement']}")
    lines_out.append(f"    applies_when: {yaml_str(g['applies_when'])}")
    if g["eval_scope"]:
        lines_out.append(f"    eval_scope: {g['eval_scope']}")
    lines_out.append(f"    statement: {yaml_str(g['statement'])}")
    lines_out.append(f"    source: {g['source']}")

print("\n".join(lines_out))
