#!/usr/bin/env bash
# README structure linter
#
# Bidirectional check:
#   1. Forward (README -> disk): every file and directory listed in
#      README.md's Structure section actually exists on disk. Prevents
#      the case where files are moved, renamed, or deleted but README
#      is not updated.
#   2. Reverse (disk -> README): every top-level file and directory in
#      the repo root is either listed in README's Structure section OR
#      appears in the README_STRUCTURE_EXCLUDE list defined below.
#      Prevents the case where a new top-level directory is added but
#      README is not updated.
#
# The reverse direction uses an explicit exclusion list for generated
# artifacts, dotfiles, and files that are intentionally omitted from
# the structure overview. Adding something to the exclusion list
# requires a one-line rationale in the comment above it.
#
# Exit 0 = pass. Exit 1 = violations found in either direction.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
README="$REPO_ROOT/README.md"

if [ ! -f "$README" ]; then
  echo "FAIL: README.md not found"
  exit 1
fi

python3 - "$REPO_ROOT" "$README" <<'PYEOF'
import sys
import os
import re

repo_root = sys.argv[1]
readme_path = sys.argv[2]

# -------------------------------------------------------------------------
# Reverse-check exclusion list (disk -> README)
#
# Top-level files and directories intentionally NOT listed in README
# Structure. Each entry has a rationale as an inline comment.
# -------------------------------------------------------------------------
README_STRUCTURE_EXCLUDE = {
    # The README itself (listing itself in its own Structure is recursive)
    "README.md",
    # Generated artifacts (auto-regenerated by pre-commit hook)
    "enforcement-spec.yml",
    "enforcement-spec-mode2-candidates.yml",
    "req-manifest.sha256",
    # Dotfiles and VCS metadata
    ".git",
    ".gitignore",
    ".github",  # listed as ".github/workflows/ci.yml" in Structure, not as a bare directory
    ".DS_Store",
    ".ese-session-state.json",  # gitignored runtime state
    ".ese-session-state.json.bak",  # ese-plugin chain-reset snapshot
    ".ese-session",  # ese-plugin per-session output cache (lint output, scaffold logs)
    ".ese-anti-pattern-draft.md",  # ese-plugin draft anti-pattern entries pending review
    ".ese-chain-reminder-state.json",  # ese-plugin chain-reminder cooldown tracking
    ".ese-chain-paused.json",  # ese-plugin paused-chain flag (set by scripts/pause-chain.sh)
    ".gate-manifest.json",  # gitignored local artifact
    ".claude",  # per-project Claude Code session state (settings.local.json, etc.); gitignored
}

with open(readme_path, encoding="utf-8") as f:
    content = f.read()

# Extract the code block from the Structure section.
# Pattern: ## Structure ... ``` ... ```
structure_match = re.search(
    r'^## Structure\s*\n.*?```\n(.*?)```',
    content,
    re.MULTILINE | re.DOTALL,
)

if not structure_match:
    print("SKIP: No Structure code block found in README.md")
    sys.exit(0)

block = structure_match.group(1)
forward_violations = []
listed_top_level = set()  # top-level names (file or dir) found in Structure

# Parse the indented tree structure.
# Each line: leading spaces + path + optional trailing description.
# Indentation determines parent directory.
# Directories end with / in their name.
dir_stack = []  # [(indent_level, dirname)]

for line in block.splitlines():
    stripped = line.strip()
    if not stripped:
        continue

    # Determine indent level (number of leading spaces / 2)
    leading = len(line) - len(line.lstrip())
    indent = leading // 2

    # Extract the path component (first non-space token).
    # Description follows after 2+ spaces.
    parts = re.split(r'\s{2,}', stripped, maxsplit=1)
    path_part = parts[0].strip()

    if not path_part:
        continue

    # Pop the directory stack to the current indent level
    while dir_stack and dir_stack[-1][0] >= indent:
        dir_stack.pop()

    # Record top-level entries (indent 0)
    if indent == 0:
        listed_top_level.add(path_part.rstrip("/"))

    # Build the full path from the directory stack
    parent = os.path.join(repo_root, *[d[1] for d in dir_stack])
    full_path = os.path.join(parent, path_part.rstrip("/"))

    is_dir = path_part.endswith("/")

    if is_dir:
        if not os.path.isdir(full_path):
            forward_violations.append(f"Directory listed but not found: {path_part.rstrip('/')}/ (expected at {os.path.relpath(full_path, repo_root)})")
        # Push this directory onto the stack for children
        dir_stack.append((indent, path_part.rstrip("/")))
    else:
        if not os.path.isfile(full_path):
            forward_violations.append(f"File listed but not found: {path_part} (expected at {os.path.relpath(full_path, repo_root)})")

# -------------------------------------------------------------------------
# Reverse check: disk -> README
# -------------------------------------------------------------------------
reverse_violations = []

for name in sorted(os.listdir(repo_root)):
    if name in README_STRUCTURE_EXCLUDE:
        continue
    if name in listed_top_level:
        continue
    full = os.path.join(repo_root, name)
    kind = "dir" if os.path.isdir(full) else "file"
    reverse_violations.append(f"Top-level {kind} '{name}' exists on disk but is not listed in README.md Structure (and is not in the exclusion list)")

# -------------------------------------------------------------------------
# Report
# -------------------------------------------------------------------------
if forward_violations or reverse_violations:
    if forward_violations:
        print("FAIL: README.md Structure section references missing paths (forward):")
        for v in forward_violations:
            print(f"  {v}")
        print()
    if reverse_violations:
        print("FAIL: README.md Structure section missing entries for on-disk items (reverse):")
        for v in reverse_violations:
            print(f"  {v}")
        print()
        print("Fix: add the entry to README.md Structure section, or add it to")
        print("README_STRUCTURE_EXCLUDE in scripts/lint-readme-structure.sh with")
        print("a one-line rationale comment if it is intentionally omitted")
        print("(e.g., generated artifact, dotfile, gitignored runtime state).")
    sys.exit(1)
else:
    print("PASS: README.md Structure matches disk in both directions (forward and reverse).")
    sys.exit(0)
PYEOF
